### ISSUE TITLE
Could you please update it？thx！

### ISSUE THREAD

**Issue by xiaoshazizizizizizizi** [bnfour/md-mods#10]
It doesn't seem to work now

**Comment by bnfour** [comment]
It still works for me, can you please describe what exactly is going wrong? What version of the mods are you using? What version of MelonLoader? What exactly happens? Are there any errors in the console or logs?

**Comment by xiaoshazizizizizizizi** [comment]
I can't install these mods, the Melonloader version is 0.6.1
![c43AfQSRMc](https://github.com/bnfour/md-mods/assets/61924682/971ea5c6-37bd-4349-8e36-95aa57dbc928)
![JXvFfSD2ik](https://github.com/bnfour/md-mods/assets/61924682/42f7fde4-d71e-46f9-ab59-6d888b07e20c)
![wgn9RCxlOA](https://github.com/bnfour/md-mods/assets/61924682/b1a9bb14-fbd8-4224-b9dc-5e2da126bcd8)

**Comment by bnfour** [comment]
Oh, I completely forgot to update the Mod Tools catalogue entries after releasing v8.

You can try to download the latest version of my mods from [releases page](https://github.com/bnfour/md-mods/releases/tag/v8) and install it manually by copying the DLL files to Mods and UserLibs folders in the game folder.

**Comment by xiaoshazizizizizizizi** [comment]
Thx！！！

**Comment by bnfour** [comment]
A quick update for anyone who might stumble upon this issue: I've updated Album scroll and True rank mods in the Mod Tools.

Scoreboard characters is now a special one that requires a feature no-one ever used before (we're not sure it even works). As such, I won't risk breaking the catalogue for now, so please download it from my repo and install manually. Sorry for the inconvenience.
