### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by Balint817** [bnfour/md-mods#7]
Hi!
Sorry for opening an issue for this, didn't really know where else to ask.
For context, [ModLinks](https://github.com/MDModsDev/ModLinks) is a repo for use with [MuseDashModTools](https://github.com/MDModsDev/MuseDashModToolsMod) and the respective [UI](https://github.com/MDModsDev/MuseDashModToolsUI).
I'd like to know if you'd be fine with these two mods being added to the list? Thanks for the answer in advance :)

**Comment by bnfour** [comment]
Hello!

Sure, I'd like to get my mods listed.
Feel free to close this issue if there is no more questions about this.

**Comment by Balint817** [comment]
No, thanks! That's all I wanted to know :)
Closing this.
